-- Run this once in the Supabase SQL editor.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  thread_id text not null,
  sender_id text not null,
  body text not null default '',
  media_type text,
  media_data text,
  created_at timestamptz not null default now()
);

create index if not exists messages_thread_created_idx
  on public.messages (thread_id, created_at);

alter table public.messages enable row level security;

-- The Streamlit server uses the Supabase service role key, so it can read/write
-- this table safely from server-side code. Do not expose that key in the browser.
